export const ROLES = {
  STUDENT: "STUDENT",
  STAFF: "STAFF",
  HOD: "HOD",
  ADMIN: "ADMIN"
};

export const COMPLAINT_STATUS = {
  ALL: "ALL",
  SUBMITTED: "SUBMITTED",
  ASSIGNED: "ASSIGNED",
  IN_PROGRESS: "IN_PROGRESS",
  RESOLVED: "RESOLVED",
  CLOSED: "CLOSED",
  ESCALATED: "ESCALATED"
};

export const SLA_RULES = {
  HOSTEL: 24,       // hours
  ACADEMIC: 48,
  EXAM: 72,
  HARASSMENT: 0     // immediate
};

export const VALID_TRANSITIONS = {
  SUBMITTED: ["ASSIGNED"],
  ASSIGNED: ["IN_PROGRESS", "ESCALATED"],
  IN_PROGRESS: ["RESOLVED", "ESCALATED"],
  RESOLVED: ["CLOSED"],
  CLOSED: [],
  ESCALATED: ["IN_PROGRESS"]
};

export const COMPLAINT_TYPES = {
  ALL: "ALL",
  HOSTEL: "HOSTEL",
  ACADEMIC: "ACADEMIC",
  EXAM: "EXAM",
  HARASSMENT: "HARASSMENT"
}
