import { COMPLAINT_STATUS } from "./constants.js";

export const VALID_TRANSITIONS = {
  [COMPLAINT_STATUS.ASSIGNED]: [
    COMPLAINT_STATUS.IN_PROGRESS
  ],
  [COMPLAINT_STATUS.IN_PROGRESS]: [
    COMPLAINT_STATUS.RESOLVED
  ],
  [COMPLAINT_STATUS.RESOLVED]: [
    COMPLAINT_STATUS.CLOSED
  ]
};
